# Generated by Django 4.2.7 on 2026-06-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL única)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notify_email', models.EmailField(help_text='Dirección de correo a la que se enviarán las notificaciones de nuevos registros.', max_length=254, verbose_name='Correo de notificación')),
                ('name_active', models.BooleanField(default=True, verbose_name='Nombre activo')),
                ('position_active', models.BooleanField(default=True, verbose_name='Puesto de trabajo activo')),
                ('email_active', models.BooleanField(default=True, verbose_name='Correo electrónico activo')),
                ('phone_active', models.BooleanField(default=True, verbose_name='Teléfono activo')),
                ('company_active', models.BooleanField(default=False, verbose_name='Empresa activa')),
                ('name_required', models.BooleanField(default=True, verbose_name='Nombre requerido')),
                ('position_required', models.BooleanField(default=True, verbose_name='Puesto de trabajo requerido')),
                ('email_required', models.BooleanField(default=True, verbose_name='Correo electrónico requerido')),
                ('phone_required', models.BooleanField(default=True, verbose_name='Teléfono requerido')),
                ('company_required', models.BooleanField(default=False, verbose_name='Empresa requerida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('job_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto de trabajo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('is_spam', models.BooleanField(default=False, verbose_name='¿Es spam?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Registro (Lead)',
                'verbose_name_plural': 'Registros (Leads)',
                'ordering': ['-created_at'],
            },
        ),
    ]
