# Generated by Django 4.2.7 on 2026-06-24 10:25

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_label',
            field=models.CharField(blank=True, default='', help_text='Texto del botón de invitación. Si se deja vacío se usa "Acceder al evento". Solo se muestra si Enlace de invitación está definido.', max_length=60, verbose_name='Texto del botón de invitación'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_link',
            field=models.URLField(blank=True, help_text='URL opcional al evento (Zoom, Meet, etc.). Se muestra únicamente en el correo de confirmación y en la pantalla de éxito tras el registro.', max_length=500, null=True, validators=[events.models._validate_http_https_url], verbose_name='Enlace de invitación'),
        ),
    ]
