# Generated by Django 4.2.7 on 2026-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_invitation_label_event_invitation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Duración estimada del evento en minutos. Debe ser mayor a 0 si se especifica una fecha y hora.', verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del evento.', null=True, verbose_name='Fecha y hora del evento'),
        ),
    ]
