# Generated by Django 4.2.7 on 2026-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_datetime_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_early_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutos antes del inicio en que se muestra el enlace de invitación. 0 = solo desde el inicio.', verbose_name='Anticipación de acceso (minutos)'),
        ),
    ]
