# Generated by Django 4.2.7 on 2025-07-10 00:12

from django.db import migrations, models
import django.db.models.deletion
import utils.text_generation


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_survey_alter_company_options_questionoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='survey_percentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de la Encuesta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.participant', verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionoption', verbose_name='Opción seleccionada de Pregunta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invitation_code',
            field=models.CharField(default=utils.text_generation.get_uuid, editable=False, max_length=255, unique=True, verbose_name='Código de Invitación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birth_range',
            field=models.CharField(choices=[('1946-1964', '1946-1964'), ('1965-1980', '1965-1980'), ('1981-1996', '1981-1996'), ('1997-2012', '1997-2012')], max_length=255, verbose_name='Rango de Edad'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Otro')], max_length=255, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('directir', 'Director'), ('manager', 'Gerente'), ('supervisor', 'Supervisor'), ('operator', 'Operador'), ('other', 'Otro')], max_length=255, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='Grupo de Preguntas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Encuesta'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='points',
            field=models.IntegerField(default=0, help_text=('Recomendado: 1 en caso de que sea una respuesta correcta, ', 'de lo contrario 0'), verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.TextField(verbose_name='Opción'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
