# Generated by Django 4.2.7 on 2025-07-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_questiongroup_survey_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='details',
            field=models.TextField(blank=True, help_text=('Detalles adicionales de la empresa. ', 'Información interna, no visible en los reportes'), null=True, verbose_name='Detalles'),
        ),
    ]
