# Generated by Django 4.2.7 on 2025-07-10 00:43

from django.db import migrations, models
import utils.text_generation


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_company_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='details',
            field=models.TextField(blank=True, help_text='Detalles adicionales de la empresa. Información interna, no visible en los reportes', null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invitation_code',
            field=models.CharField(default=utils.text_generation.get_uuid, help_text='Código de invitación para acceder a la encuesta.Ejemplo: LeadForwardNissan2025', max_length=255, unique=True, verbose_name='Código de Invitación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa. Se mostrará en los reportes', null=True, upload_to='companies/logos/', verbose_name='Logo'),
        ),
    ]
