# Generated by Django 4.2.7 on 2025-07-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_company_details_alter_company_invitation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.AddField(
            model_name='survey',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instrucciones para el participante. Se mostrarán al inicio de la encuesta.', null=True, verbose_name='Instrucciones'),
        ),
    ]
