# Generated by Django 4.2.7 on 2025-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_survey_description_survey_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_group_index',
            field=models.IntegerField(default=0, verbose_name='Posición de la pregunta en el grupo'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='survey_index',
            field=models.IntegerField(default=0, verbose_name='Posición del grupo en la encuesta'),
        ),
    ]
