# Generated by Django 4.2.7 on 2025-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_question_question_group_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='question_index',
            field=models.IntegerField(default=0, verbose_name='Posición de la opción en la pregunta'),
        ),
    ]
