# Generated by Django 4.2.7 on 2025-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_questionoption_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto'), ('select', 'Selección')], default='select', max_length=255, verbose_name='Tipo de Pregunta'),
            preserve_default=False,
        ),
    ]
