# Generated by Django 4.2.7 on 2025-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('directir', 'Director'), ('manager', 'Gerente'), ('supervisor', 'Supervisor'), ('operator', 'Operador'), ('other', 'Otro')], help_text='Posición del participante en la empresa', max_length=255, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_group_index',
            field=models.IntegerField(default=0, help_text='Posición de la pregunta en el grupo', verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='survey_index',
            field=models.IntegerField(default=0, help_text='Posición del grupo en la encuesta', verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='survey_percentage',
            field=models.FloatField(default=0, help_text='Porcentaje de la encuesta', verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question_index',
            field=models.IntegerField(default=0, help_text='Posición de la opción en la pregunta', verbose_name='Posición'),
        ),
    ]
