# Generated by Django 4.2.7 on 2025-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_participant_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_group_index',
            field=models.IntegerField(default=1, help_text='Posición de la pregunta en el grupo', verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='survey_index',
            field=models.IntegerField(default=1, help_text='Posición del grupo en la encuesta', verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question_index',
            field=models.IntegerField(default=1, help_text='Posición de la opción en la pregunta', verbose_name='Posición'),
        ),
    ]
