# Generated by Django 4.2.7 on 2025-08-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_question_question_group_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('manager', 'Gerente'), ('supervisor', 'Supervisor'), ('operator', 'Operador'), ('other', 'Otro')], help_text='Posición del participante en la empresa', max_length=255, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='points',
            field=models.IntegerField(default=0, help_text='Recomendado: 1 en caso de que sea una respuesta correcta, de lo contrario 0', verbose_name='Puntos'),
        ),
    ]
