# Generated by Django 4.2.7 on 2025-08-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Archivo PDF del reporte generado', null=True, upload_to='reports/', verbose_name='Archivo PDF'),
        ),
    ]
