# Generated by Django 4.2.7 on 2025-08-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_report_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
    ]
