# Generated by Django 4.2.7 on 2025-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total',
            field=models.FloatField(default=0, help_text='Calificación final del participante en la encuesta', verbose_name='Calificación final'),
        ),
    ]
