# Generated by Django 4.2.7 on 2025-08-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_report_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroupModifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales del modificador del formulario. ', null=True, verbose_name='Detalles')),
                ('data', models.JSONField(blank=True, help_text='Datos adicionales del modificador del formulario. Se usarán para generar el formulario.', null=True, verbose_name='Datos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modificador de Grupo de Preguntas',
                'verbose_name_plural': 'Modificadores de Grupos de Preguntas',
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='modifiers',
            field=models.ManyToManyField(help_text='Modificadores del grupo de preguntas', to='survey.questiongroupmodifier', verbose_name='Modificadores'),
        ),
    ]
