# Generated by Django 4.2.7 on 2025-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_questiongroupmodifier_questiongroup_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='modifiers',
            field=models.ManyToManyField(blank=True, help_text='Modificadores del grupo de preguntas', null=True, to='survey.questiongroupmodifier', verbose_name='Modificadores'),
        ),
    ]
