# Generated by Django 4.2.7 on 2025-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0018_alter_questiongroup_modifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="use_average",
            field=models.BooleanField(
                default=True,
                help_text="Si se desmarca esta casilla se hará uso del valor específicado",
                verbose_name="Usar Promedio",
            ),
        ),
    ]
