# Generated by Django 4.2.7 on 2025-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0019_company_use_average"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiongroup",
            name="goal_rate",
            field=models.FloatField(
                default=0,
                help_text="Valor esperado a usar en el gráfico de barras",
                verbose_name="Valor Esperado",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="use_average",
            field=models.BooleanField(
                default=True,
                help_text="Si se desmarca esta casilla se hará uso del valor específicado en el grupo de preguntas dentro del gráfico de barras",
                verbose_name="Usar Promedio en Gráfico de Barras",
            ),
        ),
    ]
