# Generated by Django 4.2.7 on 2025-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0020_questiongroup_goal_rate_alter_company_use_average"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="average_total",
            field=models.FloatField(default=0, verbose_name="Promedio Total"),
        ),
    ]
