# Generated by Django 4.2.7 on 2025-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_company_average_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='modifiers',
            field=models.ManyToManyField(help_text='Modificadores del grupo de preguntas', to='survey.questiongroupmodifier', verbose_name='Modificadores'),
        ),
    ]
