# Generated by Django 4.2.7 on 2025-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_alter_questiongroup_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='average_total',
            field=models.FloatField(default=0, help_text='Promedio de los reportes de la empresa (automáticamente calculado)', verbose_name='Promedio'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='goal_rate',
            field=models.FloatField(default=0, help_text='Valor esperado a usar en el gráfico de barras (del 1 al 10)', verbose_name='Valor Esperado'),
        ),
    ]
