# Generated by Django 4.2.7 on 2025-09-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_alter_company_average_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='modifiers',
            field=models.ManyToManyField(blank=True, help_text='Modificadores del grupo de preguntas', null=True, to='survey.questiongroupmodifier', verbose_name='Modificadores'),
        ),
    ]
