# Generated by Django 4.2.7 on 2025-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_alter_questiongroup_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error del reporte', null=True, verbose_name='Mensaje de error'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ready', '● Preparado'), ('pending', '⏳ Pendiente'), ('processing', '⚡ Procesando'), ('completed', '✔ Completado'), ('error', '✖ Error')], default='pending', help_text='Estado del reporte', max_length=255, verbose_name='Estado'),
        ),
    ]
