# Generated by Django 4.2.7 on 2025-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_report_error_message_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pendiente'), ('processing', '⚡ Procesando'), ('completed', '✔ Completado'), ('error', '✖ Error')], default='pending', help_text='Estado del reporte', max_length=255, verbose_name='Estado'),
        ),
    ]
