# Generated by Django 4.2.7 on 2025-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Mensaje de error del reporte', verbose_name='Mensaje de error'),
            preserve_default=False,
        ),
    ]
