# Generated by Django 4.2.7 on 2025-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_alter_report_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='error_message',
        ),
        migrations.AddField(
            model_name='report',
            name='logs',
            field=models.TextField(blank=True, help_text='Logs del reporte', verbose_name='Logs'),
        ),
    ]
