# Generated by Django 4.2.7 on 2025-09-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_remove_report_error_message_report_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQuestionGroupTotal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='Grupo de Preguntas')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.report', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Total de Grupo de Pregunta',
                'verbose_name_plural': 'Totales de Grupos de Preguntas',
            },
        ),
    ]
