# Generated by Django 4.2.7 on 2025-09-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_reportquestiongrouptotal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportquestiongrouptotal',
            unique_together={('report', 'question_group')},
        ),
    ]
