# Generated by Django 4.2.7 on 2025-09-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_alter_reportquestiongrouptotal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportquestiongrouptotal',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
