# Generated by Django 4.2.7 on 2025-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_alter_reportquestiongrouptotal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportquestiongrouptotal',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
