# Generated by Django 4.2.7 on 2025-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_alter_reportquestiongrouptotal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='survey_percentage',
            field=models.FloatField(default=0, help_text='Porcentaje de la encuesta (del 0 al 100)', verbose_name='Porcentaje'),
        ),
    ]
