# Generated by Django 4.2.7 on 2025-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_alter_questiongroup_survey_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroupmodifier',
            name='details_bar_chart',
            field=models.TextField(blank=True, help_text='Detalles adicionales para el gráfico de barras. ', null=True, verbose_name='Detalles (gráfico de barras)'),
        ),
        migrations.AlterField(
            model_name='questiongroupmodifier',
            name='details',
            field=models.TextField(blank=True, help_text='Detalles adicionales del modificador del formulario. ', null=True, verbose_name='Detalles (formulario)'),
        ),
    ]
