# Generated by Django 4.2.7 on 2025-09-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_questiongroupmodifier_details_bar_chart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroupmodifier',
            name='details_bar_chart',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='details_bar_chart',
            field=models.TextField(blank=True, help_text='Detalles adicionales para el gráfico de barras. ', null=True, verbose_name='Detalles (gráfico de barras)'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles (formulario)'),
        ),
        migrations.AlterField(
            model_name='questiongroupmodifier',
            name='details',
            field=models.TextField(blank=True, help_text='Información adicional del modificador.', null=True, verbose_name='Detalles'),
        ),
    ]
