# Generated by Django 4.2.7 on 2025-09-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_remove_questiongroupmodifier_details_bar_chart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('min_score', models.FloatField(default=0, verbose_name='Calificación Mínima')),
                ('section', models.CharField(choices=[('txt', 'Text'), ('prph', 'Paragraph')], max_length=255, verbose_name='Sección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='Grupo de Preguntas')),
            ],
            options={
                'verbose_name': 'Texto en PDF',
                'verbose_name_plural': 'Textos en PDF',
            },
        ),
    ]
