# Generated by Django 4.2.7 on 2025-09-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_pdftext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftext',
            name='section',
            field=models.CharField(choices=[('tlt', 'Title'), ('prph', 'Paragraph')], max_length=255, verbose_name='Sección'),
        ),
    ]
