# Generated by Django 4.2.7 on 2025-09-28 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_alter_pdftext_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPDFQuestionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('min_score', models.FloatField(default=0, verbose_name='Calificación Mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='Grupo de Preguntas')),
            ],
            options={
                'verbose_name': 'Párrafo en PDF',
                'verbose_name_plural': 'Párrafos en PDF',
            },
        ),
        migrations.CreateModel(
            name='TextPDFSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('min_score', models.FloatField(default=0, verbose_name='Calificación Mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen en PDF',
                'verbose_name_plural': 'Resumen en PDF',
            },
        ),
        migrations.DeleteModel(
            name='PdfText',
        ),
    ]
