# Generated by Django 4.2.7 on 2025-09-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_textpdfquestiongroup_textpdfsummary_delete_pdftext'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpdfsummary',
            name='paragraph_type',
            field=models.CharField(choices=[('CD', 'Cultura digital'), ('TN', 'Tecnología y negocios'), ('CS', 'Ciber seguridad'), ('IP', 'Impacto personal'), ('TMA', 'Tecnología y medio ambiente'), ('EDC', 'Ecosistema digital de colaboración')], default=1, max_length=50, verbose_name='Tipo de Párrafo'),
            preserve_default=False,
        ),
    ]
