# Generated by Django 4.2.7 on 2025-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0042_alter_textpdfquestiongroup_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpdfquestiongroup',
            name='text',
            field=models.CharField(max_length=1500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='textpdfsummary',
            name='text',
            field=models.CharField(max_length=1500, verbose_name='Texto'),
        ),
    ]
