# Generated by Django 4.2.7 on 2025-09-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_alter_textpdfquestiongroup_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textpdfquestiongroup',
            options={'verbose_name': 'PDF Párrafo', 'verbose_name_plural': 'PDF Párrafos'},
        ),
        migrations.AlterModelOptions(
            name='textpdfsummary',
            options={'verbose_name': 'PDF Resumen', 'verbose_name_plural': 'PDF Resumen'},
        ),
    ]
