# Generated by Django 4.2.7 on 2025-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_alter_textpdfquestiongroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDesiredScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_score', models.FloatField(default=0, help_text='Puntaje deseado de 0 a 100', verbose_name='Puntaje Deseado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.company', verbose_name='Empresa')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='Grupo de Preguntas')),
            ],
            options={
                'verbose_name': 'Puntaje Deseado de Grupo de Preguntas',
                'verbose_name_plural': 'Puntajes Deseados de Grupos de Preguntas',
                'unique_together': {('company', 'question_group')},
            },
        ),
    ]
