# Generated by Django 4.2.7 on 2025-10-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_companydesiredscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='goal_rate',
        ),
    ]
