# Generated by Django 4.2.7 on 2026-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0047_alter_participant_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsDownload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip_file', models.FileField(help_text='Archivo ZIP con los reportes seleccionados', upload_to='reports_downloads/zip_files/', verbose_name='Archivo ZIP (reportes)')),
                ('status', models.CharField(choices=[('pending', '⏳ Pendiente'), ('processing', '⚡ Procesando'), ('completed', '✔ Completado'), ('error', '✖ Error')], default='pending', help_text='Estado del archivo ZIP', max_length=255, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reports', models.ManyToManyField(help_text='Reportes seleccionados para descargar', related_name='reports_downloads', to='survey.report', verbose_name='Reportes')),
            ],
            options={
                'verbose_name': 'Descarga de Reportes',
                'verbose_name_plural': 'Descargas de Reportes',
            },
        ),
    ]
