# Generated by Django 4.2.7 on 2026-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_reportsdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsdownload',
            name='name',
            field=models.CharField(default='reportes.zip', help_text='Nombre del archivo ZIP', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reportsdownload',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Archivo ZIP con los reportes seleccionados', null=True, upload_to='reports_downloads/zip_files/', verbose_name='Archivo ZIP (reportes)'),
        ),
    ]
