# Generated by Django 4.2.7 on 2026-01-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_reportsdownload_name_alter_reportsdownload_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsdownload',
            name='name',
        ),
    ]
