# Generated by Django 4.2.7 on 2026-01-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_remove_reportsdownload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsdownload',
            name='logs',
            field=models.TextField(blank=True, help_text='Logs de la generación del archivo ZIP', null=True, verbose_name='Logs'),
        ),
        migrations.AlterField(
            model_name='reportsdownload',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Archivo ZIP con los reportes seleccionados', null=True, upload_to='reports_downloads/zip_files/', verbose_name='Archivo ZIP'),
        ),
    ]
