# Generated by Django 4.2.7 on 2026-01-24 22:55

from django.db import migrations, models
import django.db.models.deletion
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0051_reportsdownload_logs_alter_reportsdownload_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('current_screen', models.IntegerField(default=1, verbose_name='Pantalla actual')),
                ('data', models.JSONField(verbose_name='Datos del formulario')),
                ('expires_at', models.DateTimeField(default=survey.models.get_default_expires_at, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.company', verbose_name='Empresa')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Progreso de Formulario',
                'verbose_name_plural': 'Progresos de Formularios',
                'unique_together': {('email', 'survey')},
            },
        ),
    ]
