# Generated by Django 4.2.7 on 2026-04-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0052_formprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpdfsummary',
            name='question_groups',
            field=models.ManyToManyField(blank=True, to='survey.questiongroup', verbose_name='Grupos de Preguntas'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('analista', 'Analista'), ('asesor', 'Asesor'), ('auxiliar', 'Auxiliar'), ('contralor', 'Contralor'), ('coordinador', 'Coordinador'), ('director', 'Director'), ('director_general', 'Director General'), ('director_general_adjunto', 'Director General Adjunto'), ('enlace_informacion', 'Enlace de Información'), ('manager', 'Gerente'), ('inspector', 'Inspector'), ('investigador', 'Investigador'), ('jefe_departamento', 'Jefe de Departamento'), ('operator', 'Operador'), ('secretario_ejecutivo', 'Secretario Ejecutivo'), ('subdirector', 'Subdirector'), ('subsecretario', 'Subsecretario'), ('supervisor', 'Supervisor'), ('vicepresidente', 'Vicepresidente'), ('other', 'Otro')], help_text='Posición del participante en la empresa', max_length=255, verbose_name='Posición'),
        ),
        migrations.CreateModel(
            name='ReportSummaryScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paragraph_type', models.CharField(choices=[('CD', 'Cultura digital'), ('TN', 'Tecnología y negocios'), ('CS', 'Ciberseguridad'), ('IP', 'Impacto personal'), ('TMA', 'Tecnología y medio ambiente'), ('EDC', 'Ecosistema digital de colaboración')], max_length=50, verbose_name='Tipo de Párrafo')),
                ('score', models.FloatField(default=0, verbose_name='Calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.report', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Puntaje de Resumen de Reporte',
                'verbose_name_plural': 'Puntajes de Resúmenes de Reportes',
                'unique_together': {('report', 'paragraph_type')},
            },
        ),
    ]
