# Generated by Django 4.2.7 on 2026-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0053_participant_department_alter_participant_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'IT'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], help_text='Departamento o área del participante', max_length=255, null=True, verbose_name='Departamento'),
        ),
    ]
