# Generated by Django 4.2.7 on 2026-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0054_alter_participant_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'IT'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], help_text='Área del participante', max_length=255, null=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('analista', 'Analista'), ('asesor', 'Asesor'), ('auxiliar', 'Auxiliar'), ('contralor', 'Contralor'), ('coordinador', 'Coordinador'), ('director', 'Director'), ('director_general', 'Director General'), ('director_general_adjunto', 'Director General Adjunto'), ('enlace_informacion', 'Enlace de Información'), ('manager', 'Gerente'), ('inspector', 'Inspector'), ('investigador', 'Investigador'), ('jefe_departamento', 'Jefe de Área'), ('operator', 'Operador'), ('secretario_ejecutivo', 'Secretario Ejecutivo'), ('subdirector', 'Subdirector'), ('subsecretario', 'Subsecretario'), ('supervisor', 'Supervisor'), ('vicepresidente', 'Vicepresidente'), ('other', 'Otro')], help_text='Posición del participante en la empresa', max_length=255, verbose_name='Posición'),
        ),
    ]
