# Generated by Django 4.2.7 on 2026-05-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0054_alter_participant_department'),
        ('survey', '0054_link_summary_topics'),
    ]

    operations = [
    ]
