# Generated by Django 4.2.7 on 2026-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_alter_participant_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.CharField(blank=True, choices=[('direccion_general', 'Dirección General'), ('servicios_medicos', 'Servicios Médicos'), ('prestaciones_sociales_economicas', 'Prestaciones Sociales y Económicas'), ('administracion', 'Administración'), ('finanzas', 'Finanzas'), ('desarrollo_humano', 'Desarrollo Humano'), ('juridica', 'Jurídica'), ('comunicacion_social', 'Comunicación Social'), ('unidad_control_interno', 'Unidad Control Interno'), ('unidad_atencion_derechohabiente', 'Unidad Atención al Derechohabiente'), ('oic', 'O.I.C.')], help_text='Área del participante', max_length=255, null=True, verbose_name='Área'),
        ),
    ]
