# Generated by Django 4.2.7 on 2026-05-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_merge_20260502_1244'),
        ('survey', '0056_alter_participant_department'),
    ]

    operations = [
    ]
