# Generated by Django 4.2.7 on 2026-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_alter_participant_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_recommendations',
            field=models.TextField(blank=True, help_text='Recomendaciones personalizadas para el reporte grupal en PDF. Una por línea.', null=True, verbose_name='Recomendaciones Adicionales'),
        ),
    ]
