# Generated by Django 4.2.7 on 2026-05-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0060_company_additional_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, help_text='Archivo PDF del reporte grupal generado', null=True, upload_to='group_reports/', verbose_name='Archivo PDF')),
                ('status', models.CharField(choices=[('pending', '⏳ Pendiente'), ('processing', '⚡ Procesando'), ('completed', '✔ Completado'), ('error', '✖ Error')], default='pending', help_text='Estado del reporte grupal', max_length=255, verbose_name='Estado')),
                ('logs', models.TextField(blank=True, help_text='Logs de la generación del reporte grupal', null=True, verbose_name='Logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Empresa asociada (solo cuando se genera desde el botón de empresa)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.company', verbose_name='Empresa')),
                ('reports', models.ManyToManyField(help_text='Reportes seleccionados para el reporte grupal', related_name='group_reports', to='survey.report', verbose_name='Reportes')),
            ],
            options={
                'verbose_name': 'Reporte Grupal',
                'verbose_name_plural': 'Reportes Grupales',
            },
        ),
    ]
