# Generated by Django 4.2.7 on 2026-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_add_groupreport_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='average_total',
        ),
    ]
