# Generated by Django 4.2.7 on 2026-05-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0062_remove_company_average_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsummaryscore',
            name='paragraph_type',
            field=models.CharField(choices=[('CD', 'Cultura digital'), ('TN', 'Tecnología y negocios'), ('CS', 'Ciberseguridad'), ('IP', 'Impacto personal'), ('TMA', 'Futuro sustentable e inclusivo'), ('EDC', 'Ecosistema digital de colaboración')], max_length=50, verbose_name='Tipo de Párrafo'),
        ),
        migrations.AlterField(
            model_name='textpdfsummary',
            name='paragraph_type',
            field=models.CharField(choices=[('CD', 'Cultura digital'), ('TN', 'Tecnología y negocios'), ('CS', 'Ciberseguridad'), ('IP', 'Impacto personal'), ('TMA', 'Futuro sustentable e inclusivo'), ('EDC', 'Ecosistema digital de colaboración')], max_length=50, verbose_name='Tipo de Párrafo'),
        ),
    ]
