# Generated by Django 4.2.7 on 2026-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0063_alter_reportsummaryscore_paragraph_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsummaryscore',
            name='paragraph_type',
            field=models.CharField(choices=[('CD', 'Cultura digital'), ('TN', 'Tecnología y negocios'), ('CS', 'Ciberseguridad'), ('IP', 'Impacto personal'), ('TMA', 'Tecnología y medio ambiente'), ('EDC', 'Ecosistema digital de colaboración')], max_length=50, verbose_name='Tipo de Párrafo'),
        ),
        migrations.AlterField(
            model_name='textpdfsummary',
            name='paragraph_type',
            field=models.CharField(choices=[('CD', 'Cultura digital'), ('TN', 'Tecnología y negocios'), ('CS', 'Ciberseguridad'), ('IP', 'Impacto personal'), ('TMA', 'Tecnología y medio ambiente'), ('EDC', 'Ecosistema digital de colaboración')], max_length=50, verbose_name='Tipo de Párrafo'),
        ),
    ]
